# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serving.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serving.proto',
  package='inference',
  syntax='proto3',
  serialized_pb=_b('\n\rserving.proto\x12\tinference\"\x91\x01\n\x11\x44\x65tectionResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12 \n\x06points\x18\x02 \x03(\x0b\x32\x10.inference.Point\x12\"\n\x07objects\x18\x03 \x03(\x0b\x32\x11.inference.Object\x12(\n\nrectangles\x18\x04 \x03(\x0b\x32\x14.inference.Rectangle\"E\n\x10\x44\x65tectionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\"\n\x04rect\x18\x02 \x01(\x0b\x32\x14.inference.Rectangle\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"@\n\tRectangle\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"=\n\x06Region\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\";\n\x06Object\x12\r\n\x05label\x18\x01 \x01(\t\x12\"\n\x04rect\x18\x02 \x01(\x0b\x32\x14.inference.Rectangle2W\n\x0eShapeDetection\x12\x45\n\x06\x44\x65tect\x12\x1b.inference.DetectionRequest\x1a\x1c.inference.DetectionResponse\"\x00\x32O\n\x0fObjectDetection\x12<\n\x06\x44\x65tect\x12\x1b.inference.DetectionRequest\x1a\x11.inference.Object\"\x00\x30\x01\x62\x06proto3')
)




_DETECTIONRESPONSE = _descriptor.Descriptor(
  name='DetectionResponse',
  full_name='inference.DetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='inference.DetectionResponse.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='inference.DetectionResponse.points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objects', full_name='inference.DetectionResponse.objects', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rectangles', full_name='inference.DetectionResponse.rectangles', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=174,
)


_DETECTIONREQUEST = _descriptor.Descriptor(
  name='DetectionRequest',
  full_name='inference.DetectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='inference.DetectionRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rect', full_name='inference.DetectionRequest.rect', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=245,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='inference.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='inference.Point.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='inference.Point.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=276,
)


_RECTANGLE = _descriptor.Descriptor(
  name='Rectangle',
  full_name='inference.Rectangle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='inference.Rectangle.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='inference.Rectangle.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='inference.Rectangle.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='inference.Rectangle.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=342,
)


_REGION = _descriptor.Descriptor(
  name='Region',
  full_name='inference.Region',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='inference.Region.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='inference.Region.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='inference.Region.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='inference.Region.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=405,
)


_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='inference.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='inference.Object.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rect', full_name='inference.Object.rect', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=466,
)

_DETECTIONRESPONSE.fields_by_name['points'].message_type = _POINT
_DETECTIONRESPONSE.fields_by_name['objects'].message_type = _OBJECT
_DETECTIONRESPONSE.fields_by_name['rectangles'].message_type = _RECTANGLE
_DETECTIONREQUEST.fields_by_name['rect'].message_type = _RECTANGLE
_OBJECT.fields_by_name['rect'].message_type = _RECTANGLE
DESCRIPTOR.message_types_by_name['DetectionResponse'] = _DETECTIONRESPONSE
DESCRIPTOR.message_types_by_name['DetectionRequest'] = _DETECTIONREQUEST
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Rectangle'] = _RECTANGLE
DESCRIPTOR.message_types_by_name['Region'] = _REGION
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectionResponse = _reflection.GeneratedProtocolMessageType('DetectionResponse', (_message.Message,), dict(
  DESCRIPTOR = _DETECTIONRESPONSE,
  __module__ = 'serving_pb2'
  # @@protoc_insertion_point(class_scope:inference.DetectionResponse)
  ))
_sym_db.RegisterMessage(DetectionResponse)

DetectionRequest = _reflection.GeneratedProtocolMessageType('DetectionRequest', (_message.Message,), dict(
  DESCRIPTOR = _DETECTIONREQUEST,
  __module__ = 'serving_pb2'
  # @@protoc_insertion_point(class_scope:inference.DetectionRequest)
  ))
_sym_db.RegisterMessage(DetectionRequest)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'serving_pb2'
  # @@protoc_insertion_point(class_scope:inference.Point)
  ))
_sym_db.RegisterMessage(Point)

Rectangle = _reflection.GeneratedProtocolMessageType('Rectangle', (_message.Message,), dict(
  DESCRIPTOR = _RECTANGLE,
  __module__ = 'serving_pb2'
  # @@protoc_insertion_point(class_scope:inference.Rectangle)
  ))
_sym_db.RegisterMessage(Rectangle)

Region = _reflection.GeneratedProtocolMessageType('Region', (_message.Message,), dict(
  DESCRIPTOR = _REGION,
  __module__ = 'serving_pb2'
  # @@protoc_insertion_point(class_scope:inference.Region)
  ))
_sym_db.RegisterMessage(Region)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), dict(
  DESCRIPTOR = _OBJECT,
  __module__ = 'serving_pb2'
  # @@protoc_insertion_point(class_scope:inference.Object)
  ))
_sym_db.RegisterMessage(Object)



_SHAPEDETECTION = _descriptor.ServiceDescriptor(
  name='ShapeDetection',
  full_name='inference.ShapeDetection',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=468,
  serialized_end=555,
  methods=[
  _descriptor.MethodDescriptor(
    name='Detect',
    full_name='inference.ShapeDetection.Detect',
    index=0,
    containing_service=None,
    input_type=_DETECTIONREQUEST,
    output_type=_DETECTIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHAPEDETECTION)

DESCRIPTOR.services_by_name['ShapeDetection'] = _SHAPEDETECTION


_OBJECTDETECTION = _descriptor.ServiceDescriptor(
  name='ObjectDetection',
  full_name='inference.ObjectDetection',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=557,
  serialized_end=636,
  methods=[
  _descriptor.MethodDescriptor(
    name='Detect',
    full_name='inference.ObjectDetection.Detect',
    index=0,
    containing_service=None,
    input_type=_DETECTIONREQUEST,
    output_type=_OBJECT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBJECTDETECTION)

DESCRIPTOR.services_by_name['ObjectDetection'] = _OBJECTDETECTION

# @@protoc_insertion_point(module_scope)
